# Generated by Django 4.1.5 on 2023-01-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogsmodel',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='User1'),
        ),
        migrations.AlterField(
            model_name='dialogsmodel',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='User2'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user_mgmt.profile', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user_mgmt.profile', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='Uploaded_by'),
        ),
    ]
