# Generated by Django 4.1.5 on 2023-02-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_mgmt', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='Uploaded_by'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='chat.uploadedfile', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user_mgmt.profile', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user_mgmt.profile', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='dialogsmodel',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='User1'),
        ),
        migrations.AddField(
            model_name='dialogsmodel',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_mgmt.profile', verbose_name='User2'),
        ),
        migrations.AlterUniqueTogether(
            name='dialogsmodel',
            unique_together={('user2', 'user1'), ('user1', 'user2')},
        ),
    ]
