# Generated by Django 4.1.5 on 2023-02-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notmatches',
            old_name='not_matched_user',
            new_name='matched_user',
        ),
    ]
