# Generated by Django 4.1.5 on 2023-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='place',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='user',
            name='search_range',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
    ]
