# Generated by Django 4.1.5 on 2023-02-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='dateCreated',
            new_name='date',
        ),
    ]
