# Generated by Django 4.1.5 on 2023-05-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_alter_exercise_category_alter_gym_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=40),
        ),
    ]
