# Generated by Django 4.1.5 on 2023-03-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_rename_place_user_current_location_user_search_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='user_mgmt.location'),
        ),
    ]
