# Generated by Django 4.1.5 on 2023-05-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gym',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_mgmt.gym'),
        ),
    ]
