# Generated by Django 4.1.5 on 2023-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0004_alter_exercise_category_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
